# Build + publish a single self-contained Windows executable and upload it as an artifact.
# This workflow produces a single-file self-contained publish (exe includes .NET runtime).
name: Build and publish .NET Desktop (self-contained single-file)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Release]
        runtime: [win-x64]  # ensure a self-contained build target, change/add as needed

    env:
      Solution_Name: MiPhoneTrackHelpers.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore
      shell: pwsh
      env:
        SOLUTION: ${{ env.Solution_Name }}
      run: |
        dotnet restore $Env:SOLUTION

    - name: Publish single-file self-contained executable
      shell: pwsh
      env:
        SOLUTION: ${{ env.Solution_Name }}
        CONFIGURATION: ${{ matrix.configuration }}
        RUNTIME: ${{ matrix.runtime }}
        PUBLISH_DIR: ${{ github.workspace }}/artifacts/${{ matrix.runtime }}
      run: |
        # Create output dir
        if (-not (Test-Path -Path $Env:PUBLISH_DIR)) {
          New-Item -ItemType Directory -Path $Env:PUBLISH_DIR | Out-Null
        }

        # Produce a single-file self-contained publish
        dotnet publish $Env:SOLUTION `
          -c $Env:CONFIGURATION `
          -r $Env:RUNTIME `
          --self-contained true `
          -p:PublishSingleFile=true `
          -p:PublishTrimmed=true `
          -p:IncludeNativeLibrariesForSelfExtract=true `
          -o $Env:PUBLISH_DIR

    - name: Upload publish artifact
      uses: actions/upload-artifact@v4
      with:
        name: published-${{ matrix.runtime }}
        path: ${{ github.workspace }}/artifacts/${{ matrix.runtime }}
